app/main/log/__init__.py
from flask import Blueprint

log = Blueprint('log', __name__, url_prefix='/logs_info', template_folder='templates')
from . import views

app/main/log/views.py
# -*- coding:utf-8 -*-
from app import db
from app.models import Book, Log, Permission
from flask import render_template, url_for, flash, redirect, request, abort
from flask_login import login_required, current_user
from . import log
from ..decorators import permission_required


@log.route('/borrow/')
@login_required
@permission_required(Permission.BORROW_BOOK)
def book_borrow():
    book_id = request.args.get('book_id')
    the_book = Book.query.get_or_404(book_id)
    if the_book.hidden and not current_user.is_administrator():
        abort(404)

    result, message = current_user.borrow_book(the_book)
    flash(message, 'success' if result else 'danger')
    db.session.commit()
    return redirect(request.args.get('next') or url_for('book.detail', book_id=book_id))


@log.route('/return/')
@login_required
@permission_required(Permission.RETURN_BOOK)
def book_return():
    log_id = request.args.get('log_id')
    book_id = request.args.get('book_id')
    the_log = None
    if log_id:
        the_log = Log.query.get(log_id)
    if book_id:
        the_log = Log.query.filter_by(user_id=current_user.id, book_id=book_id).first()
    if log is None:
        flash(u'Não tem este registro!!', 'Aviso')
    else:
        result, message = current_user.return_book(the_log)
        flash(message, 'Sucesso' if result else 'Perigo')
        db.session.commit()
    return redirect(request.args.get('next') or url_for('book.detail', book_id=log_id))


@log.route('/')
@login_required
def index():
    show = request.args.get('show', 0, type=int)
    if show != 0:
        show = 1

    page = request.args.get('page', 1, type=int)
    pagination = Log.query.filter_by(returned=show).order_by(Log.borrow_timestamp.desc()).paginate(page, per_page=10)
    logs = pagination.items
    return render_template("logs_info.html", logs=logs, pagination=pagination, title=u"Informações sobre empréstimos")

app/main/log/templates/logs_info.html
{% extends "base.html" %}
{% from "bootstrap/pagination.html" import render_pagination %}
{% block mycontent %}
    <!-- Nav tabs -->
    <ul class="nav nav-tabs" role="tablist">
        {% if request.args.get('show',0)!='1' %}
            <li role="presentation" class="active"><a href="#" role="tab">
                Registros atuais</a></li>
            <li role="presentation"><a href="{{ url_for('log.index',show=1) }}" role="tab">Histórico</a></li>
        {% else %}
            <li role="presentation"><a href="{{ url_for('log.index',show=0) }}" role="tab">Registros atuais</a></li>
            <li role="presentation" class="active"><a href="#" role="tab">Histórico</a></li>
        {% endif %}
    </ul>
    <!-- Tab panes -->
    <div class="tab-content">
        {% if request.args.get('show',0)!='1' %}
            <table class="table table-striped table-hover">
                <thead class="hidden-xs">
                <tr>
                    <th>Nome</th>
                    <th>Email</th>
                    <th>Titulo</th>
                    <th>Emprestado</th>
                    <th>Vencimento</th>
                    {%- if current_user.is_authenticated -%}
                        <th class="text-center">Ação</th>
                    {%- endif -%}
                </tr>
                </thead>
                <tbody>
                {% for log in logs %}
                    <tr class="animated fadeIn delay-{{ loop.index0 }}">
                        <td><a href="{{ url_for('user.detail' ,user_id=log.user.id) }}">{{ log.user.name }}</a>
                            <a class="visible-xs-block"
                               href="{{ url_for('book.detail',book_id=log.book.id) }}">{{ log.book.title }}</a>
                            <p class="visible-xs-block">Emprestado: <span
                                    class="line-wrap">{{ log.borrow_timestamp.strftime('%d %B %Y - %H:%M:%S') }}</span>
                            </p>
                            <p class="visible-xs-block">Vencimento: <span
                                    class="line-wrap">{{ log.return_timestamp.strftime('%d %B %Y - %H:%M:%S') }}</span>
                            </p>
                            {%- if current_user.is_authenticated -%}
                                {% if current_user.id == log.user.id %}
                                    <a class="btn btn-primary visible-xs-block"
                                       href="{{ url_for('log.book_return',log_id=log.id,next=request.path) }}">
                                        Devolver
                                    </a>
                                {% else %}
                                    <button class="btn btn-warning visible-xs-block btn-block" disabled>Devolver</button>
                                {% endif %}
                            {%- endif -%}
                        </td>
                        <td class="hidden-xs">{{ log.user.email }}</td>
                        <td class="hidden-xs"><a
                                href="{{ url_for('book.detail',book_id=log.book.id) }}">{{ log.book.title }}</a></td>
                        <td class="hidden-xs">{{ log.borrow_timestamp.strftime('%d %B %Y - %H:%M:%S') }}</td>
                        <td class="hidden-xs">{{ log.return_timestamp.strftime('%d %B %Y - %H:%M:%S') }}</td>
                        {%- if current_user.is_authenticated -%}
                            <td class="hidden-xs">
                            {% if current_user.id == log.user.id %}
                                <a class="btn btn-primary btn-block"
                                   href="{{ url_for('log.book_return',log_id=log.id,next=request.path) }}">
                                   Devolver
                                </a>
                            {% else %}
                                <button class="btn btn-warning btn-block" disabled>Devolver</button>
                            {% endif %}
                        {%- endif -%}
                        </td>
                    </tr>


                {% endfor %}
                </tbody>
            </table>
        {% else %}
            <table class="table table-striped table-hover">
                <thead class="hidden-xs">
                <tr>
                    <th>Nome</th>
                    <th>Email</th>
                    <th>Titulo</th>
                    <th>Emprestado</th>
                    <th>Devolvido</th>
                </tr>
                </thead>
                <tbody>
                {% for log in logs %}
                    <tr class="animated fadeIn delay-{{ loop.index0 }}">
                        <td><a href="{{ url_for('user.detail' ,user_id=log.user.id) }}">{{ log.user.name }}</a>
                            <a class="visible-xs-block"
                               href="{{ url_for('book.detail',book_id=log.book.id) }}">{{ log.book.title }}</a>
                            <p class="visible-xs-block">: <span
                                    class="line-wrap">{{ log.borrow_timestamp.strftime('%d %B %Y - %H:%M:%S') }}</span>
                            </p>
                            <p class="visible-xs-block">: <span
                                    class="line-wrap">{{ log.return_timestamp.strftime('%d %B %Y - %H:%M:%S') }}</span>
                            </p>
                        </td>
                        <td class="hidden-xs">{{ log.user.email }}</td>
                        <td class="hidden-xs"><a
                                href="{{ url_for('book.detail',book_id=log.book.id) }}">{{ log.book.title }}</a></td>
                        <td class="hidden-xs">{{ log.borrow_timestamp.strftime('%d %B %Y - %H:%M:%S') }}</td>
                        <td class="hidden-xs">{{ log.return_timestamp.strftime('%d %B %Y - %H:%M:%S') }}</td>

                    </tr>
                {% endfor %}
                </tbody>
            </table>
            </div>
        {% endif %}
    {% if pagination and pagination.pages > 1 %}
        <div class="container-fluid text-center">
            {{ render_pagination(pagination) }}
        </div>
    {% endif %}
{% endblock %}